// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eexnsbcfuovpdjxphcmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleG5zYmNmdW92cGRqeHBoY215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDU2NjUsImV4cCI6MjA3MDAyMTY2NX0.UUF2pFZ4AQP40SI36-9RFIyTrRVY-8X8D3AvwMCfdXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});